layout_spectrum: 0.05531686
color:
  saturation: 0.9399183
  brandStrength: 0.5254759
  lightness: 0.6245972
  rhythmicContrast: 0.679377
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
typography_spectrum: 0.4591837
name: Kosel Realty
